.TH NEWSQ 1
.SH BEZEICHNUNG
newsq \- zeige die zu postenden Artikel an
.SH SYNTAX
.B newsq
.SH BESCHREIBUNG
.B Leafnode
ist ein USENET-Software-Paket, das für kleine Sites gedacht  ist, wo
es wenige User und nur geringe Festplatten-Kapazität gibt, aber
trotzdem eine große Zahl von Gruppen gewünscht wird.
.PP                             
.BR newsq
ist das Programm, das die zu postenden Artikel anzeigt, die im
Verzeichnis 
.I /var/spool/news/out.going/
aufbewahrt werden.
.SH AUTOR
Cornelius Krasel <krasel@wpxx02.toxi.uni-wuerzburg.de>.
.PP
Die ersten Versionen von leafnode wurden von Arnt Gulbrandsen
<agulbra@troll.no> geschrieben; Copyright 1995 Troll Tech AS,
Postboks 6133 Etterstad, 0602 Oslo, Norway, fax +47 22646949.
.PP
Weiterentwickelt wurde leafnode von Cornelius  Krasel
<krasel@wpxx02.toxi.uni-wuerzburg.de>, Randolf Skerka
<Randolf.Skerka@gmx.de>  und Markus Enzenberger
<enz@cip.physik.uni-muenchen.de>.
Copyright (an den Veränderungen) 1997-1999.
.PP
Die ursprüngliche Entwicklung wurde durch Uninett AS
(http://www.uninett.no/) finanziert.  
.PP
Diese Manual-Seite wurde von Joey Hess für das Debian GNU/Linux
Projekt geschrieben.
.PP
Deutsche Übersetzung:
Alexander Reinwarth <a.reinwarth@gmx.de>
.SH SIEHE AUCH
.BR leafnode (8),
.BR texpire (8),
.BR applyfilter (8),
.B fetchnews (8)
